/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Conexion;
import java.sql.Date;
import java.text.SimpleDateFormat;
import Clases.VerTabla;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Franco
 */
public class Mover extends javax.swing.JInternalFrame {

    String fecha;
    String fecha2;
    Integer hora;
    JTable principal;
    Integer condition;
    Boolean fijo;
    Integer id;
    Integer idreserva;
    Integer cancha;
    Integer canchaoriginal;
    Integer horaoriginal;
    Conexion conn = new Conexion();
    Connection con = conn.conectar();
    VerTabla v = new VerTabla();
    Date now = new Date(System.currentTimeMillis());
    public Mover(Integer ide, Boolean esfijo, JTable principa, java.util.Date fech, Integer condicion, Integer canchita, Integer horario, Integer idreservado) {
        initComponents();

        idreserva = idreservado;
        canchaoriginal = canchita;
        horaoriginal = horario;
        jDate.setDate(fech);
        String formato =  "yyyyMMdd";
        java.util.Date dsd = jDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        fecha = String.valueOf(sdf.format(dsd));
        String formato3 =  "EEEE";
        java.util.Date dsd3 = jDate.getDate();
        SimpleDateFormat sdf3 = new SimpleDateFormat(formato3);
        fecha2 = String.valueOf(sdf3.format(dsd3));
        
        principal = principa;
        fijo = esfijo;
        id = ide;
        condition = condicion;
        
        v.visualizar_tabla2(tblSeleccion, fecha, fecha2);
        
        
        tblSeleccion.setCellSelectionEnabled(true);
        tblSeleccion.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseReleased(MouseEvent evt) {
                cancha = tblSeleccion.getSelectedColumn();
                hora = Integer.parseInt(tblSeleccion.getValueAt(tblSeleccion.getSelectedRow(), 0).toString().substring(0,2));
   
        }
    });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDate.setEnabled(false);
        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tblSeleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSeleccion);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(hora == null){
            JOptionPane.showMessageDialog(null, "Seleccione un turno", "Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        if(null != tblSeleccion.getValueAt(tblSeleccion.getSelectedRow(), tblSeleccion.getSelectedColumn())){
            JOptionPane.showMessageDialog(null, "Ya hay un turno en esta cancha", "Error al guardar", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        if(fijo){
            String[] options = {"Solo Por Esta Fecha", "Mover Definitivo"};
            int seleccion = JOptionPane.showOptionDialog(null, "Desea Mover El Fijo o Solo Por Esta Fecha", "El Turno Es Fijo", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (seleccion == 1) {
                ResultSet rs = conn.visualizar_turno(hora, cancha, fecha2);
                try {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Ya hay un turno fijo en este campo", "Error al mover", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

                conn.mover(id, cancha, hora, fecha2, condition, fijo, canchaoriginal, horaoriginal, idreserva);

                String borrar = "DELETE FROM reserva WHERE id_turno = " + id + " AND fecha > '" + fecha + "' AND horario = " + horaoriginal + " AND cancha = " + canchaoriginal;
                PreparedStatement ps = null;
                try {
                    ps = con.prepareStatement(borrar);
                    ps.executeUpdate();

                } catch (Exception ex) {
                    System.out.println(ex);
                }

            } else {
                conn.canceladofijo(idreserva);
                conn.reservar(id, cancha, hora, condition, fecha, 0);
            }
        } else {
            conn.mover(id, cancha, hora, fecha, condition, fijo, canchaoriginal, horaoriginal, idreserva);
        }
        
        
        JOptionPane.showMessageDialog(null, "Turno movido", "", JOptionPane.INFORMATION_MESSAGE );
        v.visualizar_tabla2(principal, fecha, fecha2);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeleccion;
    // End of variables declaration//GEN-END:variables
}
