/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Conexion;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import Clases.VerTabla;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class Seleccion extends javax.swing.JInternalFrame {

    String fecha;
    String fecha2;
    Integer hora;
    Integer idturno;
    Integer cancha;
    Conexion conn = new Conexion();
    Connection con = conn.conectar();
    VerTabla v = new VerTabla();
    Date now = new Date(System.currentTimeMillis());
    public Seleccion(Integer id) {
        initComponents();
        idturno = id;
        
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(now);
        int calendarTime = Calendar.DAY_OF_MONTH;
        int temp = calendar.get(calendarTime);
        calendar.set(calendarTime, temp+1);

        
        jDate.setSelectableDateRange(calendar.getTime(), null);
        calendar.set(calendarTime, temp+7);
        jDate.setDate(calendar.getTime());
        
        String formato =  "yyyyMMdd";
        java.util.Date dsd = jDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        fecha = String.valueOf(sdf.format(dsd));
        String formato3 =  "EEEE";
        java.util.Date dsd3 = jDate.getDate();
        SimpleDateFormat sdf3 = new SimpleDateFormat(formato3);
        fecha2 = String.valueOf(sdf3.format(dsd3));
        
        v.visualizar_tabla2(tblSeleccion, fecha, fecha2);
        
        
        jDate.getDateEditor().addPropertyChangeListener("date", new PropertyChangeListener(){ 
            public void propertyChange(PropertyChangeEvent e) {
                String formato =  "yyyyMMdd";
                java.util.Date dsd = jDate.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                fecha = String.valueOf(sdf.format(dsd));
                String formato3 =  "EEEE";
                java.util.Date dsd3 = jDate.getDate();
                SimpleDateFormat sdf3 = new SimpleDateFormat(formato3);
                fecha2 = String.valueOf(sdf3.format(dsd3));
                v.visualizar_tabla2(tblSeleccion, fecha, fecha2);

            }
        });

        
        
        tblSeleccion.setCellSelectionEnabled(true);
        tblSeleccion.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseReleased(MouseEvent evt) {
                cancha = tblSeleccion.getSelectedColumn();
                hora = Integer.parseInt(tblSeleccion.getValueAt(tblSeleccion.getSelectedRow(), 0).toString().substring(0,2));
   
        }
    });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tblSeleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSeleccion);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(hora == null){
            JOptionPane.showMessageDialog(null, "Seleccione un turno", "Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        if(null != tblSeleccion.getValueAt(tblSeleccion.getSelectedRow(), tblSeleccion.getSelectedColumn())){
            JOptionPane.showMessageDialog(null, "Ya hay un turno en esta cancha", "Error al guardar", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String[] options = {"Solo Por Esta Fecha", "Turno Fijo"};
            int seleccion = JOptionPane.showOptionDialog(null, "Desea Reservar Solo Por Esta Fecha o Dejar El Turno Fijo", "Reserva De Turno", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (seleccion == 1) {
                ResultSet rs = conn.visualizar_turno(hora, cancha, fecha2);
                try {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Ya hay un turno fijo en este campo", "Error Al Copiar", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                conn.reservar(idturno, cancha, hora, 0, fecha2, 1);
            }else{
                conn.reservar(idturno, cancha, hora, 0, fecha, 0);
            }

        JOptionPane.showMessageDialog(null, "Turno guardado", "", JOptionPane.INFORMATION_MESSAGE );
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeleccion;
    // End of variables declaration//GEN-END:variables
}
